sonar.projectKey=election-process-assistant
sonar.sources=src
sonar.tests=src,tests
sonar.test.inclusions=**/*.spec.ts,**/tests/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/functions/lib/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json
